---
# tasks file for ansible-role-dnsclient
- name: dns client configure
  template: 
    src: resolv.conf.j2 
    dest:  "{{ resolver_config_file }}"
    owner: "{{ resolver_config_file_owner }}"
    group: "{{ resolver_config_file_group }}"
    mode:  "{{ resolver_config_file_mode }}"

